# Generated by Django 4.2.2 on 2023-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('doc_file', models.FileField(default='Página Documentos/Documentos/default.docx', upload_to='Página Documentos/Documentos', verbose_name='Archivos')),
            ],
            options={
                'verbose_name': 'Documento rápido',
                'verbose_name_plural': 'Documentos rápidos',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Encabezado_Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
                ('texto_2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Documento',
                'verbose_name_plural': 'Encabezado Documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, default='Sección de Documentos', max_length=100)),
            ],
            options={
                'verbose_name': 'Seccion de documentos',
                'verbose_name_plural': 'Secciones de documentos',
                'db_table': 'section',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Texto_Documentos_Rapidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Texto Documentos Rápidos',
                'verbose_name_plural': 'Texto Documentos Rápidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('doc_file', models.FileField(default='Página Documentos/Documentos/default.docx', upload_to='Página Documentos/Documentos', verbose_name='Archivo')),
                ('seccion', models.ManyToManyField(to='Documentos.seccion', verbose_name='sección')),
            ],
            options={
                'verbose_name': 'Documento',
                'db_table': 'documento',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
    ]
