# Generated by Django 4.2.2 on 2023-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='doc_file',
            field=models.FileField(default='Pagina-Documentos/Documentos/default.docx', upload_to='Pagina-Documentos/Documentos', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentorap',
            name='doc_file',
            field=models.FileField(default='Pagina-Documentos/Documentos/default.docx', upload_to='Pagina-Documentos/Documentos', verbose_name='Archivos'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='texto',
            field=models.CharField(default='Sección de Documentos', max_length=100),
        ),
    ]
