# Generated by Django 4.1.1 on 2023-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0004_alter_contrato_específico_columna_1_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CendaDocumentsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Texto para título de sección Registro / Certificación de SW CENDA',
                'verbose_name_plural': 'Texto para título de sección Registro / Certificación de SW CENDA',
                'db_table': 'document_title_Cenda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralContractTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Texto para título de sección Contrato general',
                'verbose_name_plural': 'Texto para título de sección Contrato general',
                'db_table': 'document_title_general_contract',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MiconsDocumentsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Texto para título de sección Registro / Certificación SW MICONS',
                'verbose_name_plural': 'Texto para título de sección Registro / Certificación SW MICONS',
                'db_table': 'document_title_sw_micons',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OtherDocumentsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Texto para título de sección Otros Documentos',
                'verbose_name_plural': 'Texto para título de sección Otros Documentos',
                'db_table': 'document_title_other_documents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesProductsListTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Texto para título de sección Listado de Productos y Servicios',
                'verbose_name_plural': 'Texto para título de sección Listado de Productos y Servicios',
                'db_table': 'document_title_products_services_list',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificContractTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Texto para título de sección Contrato Específico',
                'verbose_name_plural': 'Texto para título de sección Contrato Específico',
                'db_table': 'document_title_specific_contract',
                'ordering': ['id'],
            },
        ),
    ]
