# Generated by Django 4.1.1 on 2023-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0005_cendadocumentstitle_generalcontracttitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cendadocumentstitle',
            name='texto',
            field=models.CharField(blank=True, default='Documentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalcontracttitle',
            name='texto',
            field=models.CharField(blank=True, default='Documentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='miconsdocumentstitle',
            name='texto',
            field=models.CharField(blank=True, default='Documentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='otherdocumentstitle',
            name='texto',
            field=models.CharField(blank=True, default='Documentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicesproductslisttitle',
            name='texto',
            field=models.CharField(blank=True, default='Documentos', max_length=100),
        ),
        migrations.AlterField(
            model_name='specificcontracttitle',
            name='texto',
            field=models.CharField(blank=True, default='Documentos', max_length=100),
        ),
    ]
