# Generated by Django 4.1.1 on 2023-06-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0007_documento_documentorap_seccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'managed': True, 'ordering': ['nombre'], 'verbose_name': 'Documento'},
        ),
        migrations.AlterModelTable(
            name='documento',
            table='documento',
        ),
    ]
