# Generated by Django 4.2.2 on 2023-07-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion_Servicios_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
            ],
            options={
                'verbose_name': 'Descripción Servicio Aicros',
                'verbose_name_plural': 'Descripción Servicio Aicros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Encabezado_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
                ('texto_2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Servicio',
                'verbose_name_plural': 'Encabezado Servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_carrusel', models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Página Servicios/Servicios', verbose_name='Foto Carrusel')),
                ('show', models.BooleanField(default=True, verbose_name='Mostrar en carrusel')),
                ('show_text', models.BooleanField(default=True, verbose_name='Mostrar texto')),
                ('show_image', models.BooleanField(default=True, verbose_name='Mostrar imagen')),
                ('descripción', models.TextField()),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sweb.líneas_de_negocio', verbose_name='Línea de negocio')),
            ],
            options={
                'verbose_name': 'Servicio Aicros',
                'verbose_name_plural': 'Servicio Aicros',
                'ordering': ['id'],
            },
        ),
    ]
