# Generated by Django 4.1.1 on 2023-04-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0063_alter_cifra_options'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_aicros',
            name='line_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sweb.líneas_de_negocio', verbose_name='Línea de negocio'),
            preserve_default=False,
        ),
    ]
