# Generated by Django 4.2.2 on 2023-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio_aicros',
            options={'ordering': ['line_id'], 'verbose_name': 'Servicio Aicros', 'verbose_name_plural': 'Servicio Aicros'},
        ),
        migrations.AlterField(
            model_name='servicio_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Pagina-Servicios/Servicios', verbose_name='Foto Carrusel'),
        ),
    ]
