# Generated by Django 4.1.1 on 2023-04-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0063_alter_cifra_options'),
        ('Servicios', '0002_servicio_aicros_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_aicros',
            name='line_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Sweb.líneas_de_negocio', verbose_name='Línea de negocio'),
        ),
    ]
