# Generated by Django 4.1.1 on 2023-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_alter_servicio_aicros_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_aicros',
            name='ícono',
        ),
        migrations.AddField(
            model_name='servicio_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, null=True, upload_to='Página Servicios\\Servicios', verbose_name='Foto Carrusel'),
        ),
        migrations.AddField(
            model_name='servicio_aicros',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Mostrar en carrusel'),
        ),
        migrations.AddField(
            model_name='servicio_aicros',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Mostrar imagen'),
        ),
        migrations.AddField(
            model_name='servicio_aicros',
            name='show_text',
            field=models.BooleanField(default=True, verbose_name='Mostrar texto'),
        ),
    ]
