# Generated by Django 4.1.1 on 2023-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_alter_servicio_aicros_foto_carrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', null=True, upload_to='Página Servicios/Servicios', verbose_name='Foto Carrusel'),
        ),
    ]
