# Generated by Django 3.2.9 on 2022-09-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tproducto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tproducto',
            name='name',
        ),
    ]
