# Generated by Django 4.2.2 on 2023-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page404',
            options={'ordering': ['id'], 'verbose_name': 'Pagina-404'},
        ),
        migrations.AlterField(
            model_name='alianza',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Pagina-Home/Alianzas'),
        ),
        migrations.AlterField(
            model_name='líneas_de_negocio',
            name='ícono',
            field=models.ImageField(blank=True, null=True, upload_to='Pagina-Home/Lineas-de-Negocio'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(default='../static/img/AicrosIdentificador.png', upload_to='Pagina-Home/Noticias/'),
        ),
        migrations.AlterField(
            model_name='page404',
            name='foto',
            field=models.ImageField(blank=True, default='../static/img/logo/invertido.png', upload_to='Pagina-Home/'),
        ),
    ]
