# Generated by Django 4.1.1 on 2022-09-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0003_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
