# Generated by Django 4.1.1 on 2022-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0004_documento_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
