# Generated by Django 4.1.1 on 2022-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0006_alter_documento_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentosPage/documentosWord'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='documentosPage/documentosIcon'),
        ),
    ]
