# Generated by Django 4.1.1 on 2022-09-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0007_alter_documento_documentos_alter_documento_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='title',
        ),
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='Página Documentos/Contratos'),
        ),
        migrations.AddField(
            model_name='documento',
            name='ícono',
            field=models.ImageField(blank=True, null=True, upload_to='Página Documentos/Ícono'),
        ),
    ]
