# Generated by Django 4.1.1 on 2022-10-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0008_rename_name_documento_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_Columna1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Columna 1/Contratos')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Columna 1/Ícono')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento_Columna2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Columna 2/Contratos')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Columna 2/Ícono')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento_Columna3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Columna 3/Contratos')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Columna 3/Ícono')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
