# Generated by Django 4.1.1 on 2022-10-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0009_documento_columna1_documento_columna2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_Columna1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Columna 1/Contratos')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Columna 1/Ícono')),
            ],
            options={
                'verbose_name': 'Contrato Columna 1',
                'verbose_name_plural': 'Contrato Columna 1',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato_Columna2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Columna 2/Contratos')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Columna 2/Ícono')),
            ],
            options={
                'verbose_name': 'Contrato Columna 2',
                'verbose_name_plural': 'Contrato Columna 2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contrato_Columna3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Columna 3/Contratos')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Columna 3/Ícono')),
            ],
            options={
                'verbose_name': 'Contrato Columna 3',
                'verbose_name_plural': 'Contrato Columna 3',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Documento_Columna1',
        ),
        migrations.DeleteModel(
            name='Documento_Columna2',
        ),
        migrations.DeleteModel(
            name='Documento_Columna3',
        ),
    ]
