# Generated by Django 4.1.1 on 2022-10-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0010_contrato_columna1_contrato_columna2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Líneas_de_Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Home/Líneas de Negocio/Ícono')),
                ('título', models.CharField(max_length=500)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Líneas de Negocio',
                'verbose_name_plural': 'Líneas de Negocio',
                'ordering': ['título'],
            },
        ),
        migrations.RenameField(
            model_name='contrato_columna1',
            old_name='icono',
            new_name='ícono',
        ),
        migrations.RenameField(
            model_name='contrato_columna2',
            old_name='icono',
            new_name='ícono',
        ),
        migrations.RenameField(
            model_name='contrato_columna3',
            old_name='icono',
            new_name='ícono',
        ),
    ]
