# Generated by Django 4.1.1 on 2022-10-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0011_líneas_de_negocio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='líneas_de_negocio',
            options={'ordering': ['id'], 'verbose_name': 'Líneas de Negocio', 'verbose_name_plural': 'Líneas de Negocio'},
        ),
        migrations.RemoveField(
            model_name='líneas_de_negocio',
            name='título',
        ),
    ]
