# Generated by Django 4.1.1 on 2022-10-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0012_alter_líneas_de_negocio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encabezado_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto1', models.TextField()),
                ('texto2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Producto',
                'verbose_name_plural': 'Encabezado Producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgProd', models.ImageField(blank=True, null=True, upload_to='Página Productos/Aicros/Imágenes')),
                ('descripción', models.TextField()),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Productos/Aicros/Ícono')),
                ('nombre_botón', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Producto Aicros',
                'verbose_name_plural': 'Producto Aicros',
                'ordering': ['id'],
            },
        ),
    ]
