# Generated by Django 4.1.1 on 2022-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0013_encabezado_producto_producto_aicros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_aicros',
            old_name='imgProd',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto_aicros',
            old_name='nombre_botón',
            new_name='nombre_Botón',
        ),
        migrations.AddField(
            model_name='producto_aicros',
            name='título',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
