# Generated by Django 4.1.1 on 2022-10-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0014_rename_imgprod_producto_aicros_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_aicros',
            old_name='imagen',
            new_name='foto',
        ),
    ]
