# Generated by Django 4.1.1 on 2022-10-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0015_rename_imagen_producto_aicros_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Distribuido_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Página Productos/Aicros/Distribuidos/Imágenes')),
                ('título', models.CharField(blank=True, max_length=200, null=True)),
                ('descripción', models.TextField()),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Productos/Aicros/Distribuidos/Ícono')),
                ('nombre_Botón', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Producto Distribuido Aicros',
                'verbose_name_plural': 'Producto Distribuido Aicros',
                'ordering': ['id'],
            },
        ),
    ]
