# Generated by Django 4.1.1 on 2022-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0016_producto_distribuido_aicros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato_Específico_Columna_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Contratos Específicos/Documentos/Columna 1')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Contratos Específicos/Íconos/Columna 1')),
            ],
            options={
                'verbose_name': 'Contrato Específico Columna 1',
                'verbose_name_plural': 'Contrato Específico Columna 1',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato_Específico_Columna_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Contratos Específicos/Documentos/Columna 2')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Contratos Específicos/Íconos/Columna 2')),
            ],
            options={
                'verbose_name': 'Contrato Específico Columna 2',
                'verbose_name_plural': 'Contrato Específico Columna 2',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato_Específico_Columna_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Contratos Específicos/Documentos/Columna 3')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Contratos Específicos/Íconos/Columna 3')),
            ],
            options={
                'verbose_name': 'Contrato Específico Columna 3',
                'verbose_name_plural': 'Contrato Específico Columna 3',
                'ordering': ['nombre'],
            },
        ),
    ]
