# Generated by Django 4.1.1 on 2022-10-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0017_contrato_específico_columna_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado_Productos_y_Servicios_Columna_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Listado Productos y Servicios/Documentos/Columna 1')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Listado Productos y Servicios/Íconos/Columna 1')),
            ],
            options={
                'verbose_name': 'Listado Productos y Servicios Columna 1',
                'verbose_name_plural': 'Listado Productos y Servicios Columna 1',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Listado_Productos_y_Servicios_Columna_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Listado Productos y Servicios/Documentos/Columna 2')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Listado Productos y Servicios/Íconos/Columna 2')),
            ],
            options={
                'verbose_name': 'Listado Productos y Servicios Columna 2',
                'verbose_name_plural': 'Listado Productos y Servicios Columna 2',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Listado_Productos_y_Servicios_Columna_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Listado Productos y Servicios/Documentos/Columna 3')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Listado Productos y Servicios/Íconos/Columna 3')),
            ],
            options={
                'verbose_name': 'Listado Productos y Servicios Columna 3',
                'verbose_name_plural': 'Listado Productos y Servicios Columna 3',
                'ordering': ['nombre'],
            },
        ),
    ]
