# Generated by Django 4.1.1 on 2022-10-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0020_contrato_general_columna_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otros_Documentos_Columna_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Otros Documentos/Documentos/Columna 1')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Otros Documentos/Íconos/Columna 1')),
            ],
            options={
                'verbose_name': 'Otro Documento Columna 1',
                'verbose_name_plural': 'Otro Documento Columna 1',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Otros_Documentos_Columna_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Otros Documentos/Documentos/Columna 2')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Otros Documentos/Íconos/Columna 2')),
            ],
            options={
                'verbose_name': 'Otro Documento Columna 2',
                'verbose_name_plural': 'Otro Documento Columna 2',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Otros_Documentos_Columna_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Otros Documentos/Documentos/Columna 3')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Otros Documentos/Íconos/Columna 3')),
            ],
            options={
                'verbose_name': 'Otro Documento Columna 3',
                'verbose_name_plural': 'Otro Documento Columna 3',
                'ordering': ['nombre'],
            },
        ),
    ]
