# Generated by Django 4.1.1 on 2022-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0021_otros_documentos_columna_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encabezado_Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto1', models.TextField()),
                ('texto2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Documento',
                'verbose_name_plural': 'Encabezado Documento',
                'ordering': ['id'],
            },
        ),
    ]
