# Generated by Django 4.1.1 on 2022-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0023_rename_texto1_encabezado_documentos_texto_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto_Documentos_Rapidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Texto Documentos Rápidos',
                'verbose_name_plural': 'Texto Documentos Rápidos',
                'ordering': ['id'],
            },
        ),
    ]
