# Generated by Django 4.1.1 on 2022-10-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0024_texto_documentos_rapidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos_de_Rápido_Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='Página Documentos/Documentos de Rápido Acceso/Documentos/Columna 1')),
                ('ícono', models.ImageField(blank=True, null=True, upload_to='Página Documentos/Documentos de Rápido Acceso/Íconos/Columna 1')),
            ],
            options={
                'verbose_name': 'Texto para Documentos Rápidos',
                'verbose_name_plural': 'Texto para Documentos Rápidos',
                'ordering': ['nombre'],
            },
        ),
    ]
