# Generated by Django 4.1.1 on 2022-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0027_descripcion_servicios_aicros_encabezado_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encabezado_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
                ('texto_2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Nosotros',
                'verbose_name_plural': 'Encabezado Nosotros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mision_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misión',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Valores_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Valores',
                'verbose_name_plural': 'Valores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vision_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Visión',
                'verbose_name_plural': 'Visión',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='descripcion_servicios_aicros',
            options={'ordering': ['id'], 'verbose_name': 'Descripción Servicio Aicros', 'verbose_name_plural': 'Descripción Servicio Aicros'},
        ),
        migrations.AlterModelOptions(
            name='servicio_aicros',
            options={'ordering': ['id'], 'verbose_name': 'Servicio Aicros', 'verbose_name_plural': 'Servicio Aicros'},
        ),
    ]
