# Generated by Django 4.1.1 on 2022-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0028_encabezado_nosotros_mision_nosotros_valores_nosotros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_Columna_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Evento Columna 1',
                'verbose_name_plural': 'Evento Columna 1',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento_Columna_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Evento Columna 2',
                'verbose_name_plural': 'Evento Columna 2',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento_Columna_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Evento Columna 3',
                'verbose_name_plural': 'Evento Columna 3',
                'ordering': ['id'],
            },
        ),
    ]
