# Generated by Django 4.1.1 on 2022-10-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0029_evento_columna_1_evento_columna_2_evento_columna_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anno_Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('número', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Año de Historia',
                'verbose_name_plural': 'Año de Historia',
                'ordering': ['número'],
            },
        ),
    ]
