# Generated by Django 4.1.1 on 2022-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0030_anno_historia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Miembro_de_Trabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Nosotros/Miembro de Trabajo/Imágenes",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Miembro de Trabajo",
                "verbose_name_plural": "Miembro de Trabajo",
                "ordering": ["cargo"],
            },
        ),
    ]
