# Generated by Django 4.1.1 on 2022-10-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0031_miembro_de_trabajo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="miembro_de_trabajo",
            options={
                "ordering": ["id"],
                "verbose_name": "Miembro de Trabajo",
                "verbose_name_plural": "Miembro de Trabajo",
            },
        ),
        migrations.AlterModelOptions(
            name="tproducto",
            options={
                "ordering": ["id"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Producto",
            },
        ),
        migrations.RenameField(
            model_name="tproducto",
            old_name="picture",
            new_name="foto",
        ),
        migrations.AddField(
            model_name="tproducto",
            name="descripción",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tproducto",
            name="título",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
