# Generated by Django 4.1.1 on 2022-10-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0032_alter_miembro_de_trabajo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cifra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=200)),
                ("número", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Cifra",
                "verbose_name_plural": "Cifra",
                "ordering": ["título"],
            },
        ),
        migrations.AlterField(
            model_name="tproducto",
            name="descripción",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tproducto",
            name="título",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
