# Generated by Django 4.1.1 on 2022-10-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0033_cifra_alter_tproducto_descripción_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrusel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="productosFotos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ímagen para Carrusel",
                "verbose_name_plural": "Ímagen para Carrusel",
                "db_table": "Ímagen para Carrusel",
                "ordering": ["id"],
            },
        ),
    ]
