# Generated by Django 4.1.1 on 2022-10-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0034_carrusel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrusel",
            name="texto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
