# Generated by Django 4.1.1 on 2022-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0035_alter_carrusel_texto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrusel_Servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(blank=True, max_length=50, null=True)),
                ("descripción", models.TextField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Home/Servicios/Imágenes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio para Carrusel",
                "verbose_name_plural": "Servicio para Carrusel",
                "db_table": "Carrusel_Servicios",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InicioServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("título", models.CharField(max_length=50)),
                ("descripción", models.TextField()),
            ],
            options={
                "verbose_name": "Caja de Servicios",
                "verbose_name_plural": "Caja de Servicios",
                "db_table": "Caja de Servicios",
                "ordering": ["id"],
            },
        ),
    ]
