# Generated by Django 4.1.1 on 2022-10-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0036_carrusel_servicios_inicioservicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inicioservicio",
            name="descripción",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inicioservicio",
            name="título",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
