# Generated by Django 4.1.1 on 2022-10-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0037_alter_inicioservicio_descripción_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrusel_servicios",
            name="título",
        ),
    ]
