# Generated by Django 4.1.1 on 2022-10-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0038_remove_carrusel_servicios_título"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Anno_Historia",
        ),
        migrations.DeleteModel(
            name="Descripcion_Productos_Aicros",
        ),
        migrations.DeleteModel(
            name="Descripcion_Productos_Distribuidos",
        ),
        migrations.DeleteModel(
            name="Encabezado_Nosotros",
        ),
        migrations.DeleteModel(
            name="Encabezado_Producto",
        ),
        migrations.DeleteModel(
            name="Evento_Columna_1",
        ),
        migrations.DeleteModel(
            name="Evento_Columna_2",
        ),
        migrations.DeleteModel(
            name="Evento_Columna_3",
        ),
        migrations.DeleteModel(
            name="Miembro_de_Trabajo",
        ),
        migrations.DeleteModel(
            name="Mision_Nosotros",
        ),
        migrations.DeleteModel(
            name="Producto_Aicros",
        ),
        migrations.DeleteModel(
            name="Producto_Distribuido_Aicros",
        ),
        migrations.DeleteModel(
            name="Valores_Nosotros",
        ),
        migrations.DeleteModel(
            name="Vision_Nosotros",
        ),
    ]
