# Generated by Django 4.1.1 on 2022-10-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0039_delete_anno_historia_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contrato_Específico_Columna_1",
        ),
        migrations.DeleteModel(
            name="Contrato_Específico_Columna_2",
        ),
        migrations.DeleteModel(
            name="Contrato_Específico_Columna_3",
        ),
        migrations.DeleteModel(
            name="Contrato_General_Columna_1",
        ),
        migrations.DeleteModel(
            name="Contrato_General_Columna_2",
        ),
        migrations.DeleteModel(
            name="Contrato_General_Columna_3",
        ),
        migrations.DeleteModel(
            name="Documentos_de_Rápido_Acceso",
        ),
        migrations.DeleteModel(
            name="Encabezado_Documentos",
        ),
        migrations.DeleteModel(
            name="Listado_Productos_y_Servicios_Columna_1",
        ),
        migrations.DeleteModel(
            name="Listado_Productos_y_Servicios_Columna_2",
        ),
        migrations.DeleteModel(
            name="Listado_Productos_y_Servicios_Columna_3",
        ),
        migrations.DeleteModel(
            name="Otros_Documentos_Columna_1",
        ),
        migrations.DeleteModel(
            name="Otros_Documentos_Columna_2",
        ),
        migrations.DeleteModel(
            name="Otros_Documentos_Columna_3",
        ),
        migrations.DeleteModel(
            name="Registro_y_Certificaciones_de_Software_Columna_1",
        ),
        migrations.DeleteModel(
            name="Registro_y_Certificaciones_de_Software_Columna_2",
        ),
        migrations.DeleteModel(
            name="Registro_y_Certificaciones_de_Software_Columna_3",
        ),
        migrations.DeleteModel(
            name="Texto_Documentos_Rapidos",
        ),
    ]
