# Generated by Django 4.1.1 on 2022-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0040_delete_contrato_específico_columna_1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Descripcion_Servicios_Aicros",
        ),
        migrations.DeleteModel(
            name="Encabezado_Servicio",
        ),
        migrations.DeleteModel(
            name="Servicio_Aicros",
        ),
    ]
