# Generated by Django 4.1.1 on 2022-10-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0041_delete_descripcion_servicios_aicros_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Home/Noticias/Noticia 1/Ímagen",
                    ),
                ),
                ("Introducción_de_Noticia", models.TextField()),
                ("Continuación_de_Noticia", models.TextField()),
                ("Fecha", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Noticia 1",
                "verbose_name_plural": "Noticia 1",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Noticia_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Home/Noticias/Noticia 2/Ímagen",
                    ),
                ),
                ("Introducción_de_Noticia", models.TextField()),
                ("Continuación_de_Noticia", models.TextField()),
                ("Fecha", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Noticia 2",
                "verbose_name_plural": "Noticia 2",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Noticia_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Página Home/Noticias/Noticia 3/Ímagen",
                    ),
                ),
                ("Introducción_de_Noticia", models.TextField()),
                ("Continuación_de_Noticia", models.TextField()),
                ("Fecha", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Noticia 3",
                "verbose_name_plural": "Noticia 3",
                "ordering": ["id"],
            },
        ),
    ]
