# Generated by Django 4.1.1 on 2022-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0042_noticia_1_noticia_2_noticia_3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alianza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="Página Home/Alianzas/Ímagen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Alianza",
                "verbose_name_plural": "Alianza",
                "ordering": ["id"],
            },
        ),
    ]
