# Generated by Django 4.1.1 on 2022-10-30 04:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0043_alianza"),
    ]

    operations = [
        migrations.AddField(
            model_name="cifra",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
