# Generated by Django 4.1.1 on 2022-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0044_cifra_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tproducto",
            name="descripción",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
