# Generated by Django 4.1.1 on 2022-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0045_alter_tproducto_descripción"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia_1",
            name="título",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="noticia_2",
            name="título",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="noticia_3",
            name="título",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
