# Generated by Django 4.1.1 on 2022-11-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0046_noticia_1_título_noticia_2_título_noticia_3_título"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TProducto",
            new_name="Carrusel_Productos",
        ),
    ]
