# Generated by Django 4.1.1 on 2022-11-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Sweb", "0047_rename_tproducto_carrusel_productos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrusel",
            options={
                "ordering": ["id"],
                "verbose_name": "Ímagen para Carrusel de Promociones",
                "verbose_name_plural": "Ímagen para Carrusel de Promociones",
            },
        ),
        migrations.AlterModelOptions(
            name="carrusel_productos",
            options={
                "ordering": ["id"],
                "verbose_name": "Producto para Carrusel",
                "verbose_name_plural": "Producto para Carrusel",
            },
        ),
        migrations.AlterModelOptions(
            name="líneas_de_negocio",
            options={
                "ordering": ["id"],
                "verbose_name": "Línea de Negocio",
                "verbose_name_plural": "Línea de Negocio",
            },
        ),
        migrations.AlterModelTable(
            name="carrusel",
            table="Ímagen para Carrusel de Promociones",
        ),
    ]
