# Generated by Django 4.1.1 on 2023-03-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0048_alter_carrusel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrusel',
            options={'ordering': ['id'], 'verbose_name': 'Ímagen_para_Carrusel_de_Promociones', 'verbose_name_plural': 'Ímagen_para_Carrusel_de_Promociones'},
        ),
        migrations.AlterModelOptions(
            name='inicioservicio',
            options={'ordering': ['id'], 'verbose_name': 'Caja_de_Servicios', 'verbose_name_plural': 'Caja_de_Servicios'},
        ),
        migrations.AlterModelTable(
            name='carrusel',
            table='Ímagen_para_Carrusel_de_Promociones',
        ),
        migrations.AlterModelTable(
            name='inicioservicio',
            table='Caja_de_Servicios',
        ),
    ]
