# Generated by Django 4.1.1 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0050_alter_noticia_1_introducción_de_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia_1',
            name='Introducción_de_Noticia',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia_2',
            name='Introducción_de_Noticia',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia_3',
            name='Introducción_de_Noticia',
            field=models.TextField(max_length=200),
        ),
    ]
