# Generated by Django 4.1.1 on 2023-03-29 15:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0051_alter_noticia_1_introducción_de_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifra',
            name='color',
            field=colorfield.fields.ColorField(default='#991A14', image_field=None, max_length=18, samples=None),
        ),
    ]
