# Generated by Django 4.1.1 on 2023-03-29 18:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0052_alter_cifra_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cifra',
            name='font_color',
            field=colorfield.fields.ColorField(default='#FFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
