# Generated by Django 4.1.1 on 2023-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0053_cifra_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel_productos',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrusel_productos',
            name='show_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrusel_servicios',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrusel_servicios',
            name='show_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrusel_servicios',
            name='título',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
