# Generated by Django 4.1.1 on 2023-03-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0054_carrusel_productos_show_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel_productos',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Mostrar imagen'),
        ),
        migrations.AlterField(
            model_name='carrusel_productos',
            name='show_text',
            field=models.BooleanField(default=True, verbose_name='Mostrar texto'),
        ),
        migrations.AlterField(
            model_name='carrusel_servicios',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Mostrar imagen'),
        ),
        migrations.AlterField(
            model_name='carrusel_servicios',
            name='show_text',
            field=models.BooleanField(default=True, verbose_name='Mostrar texto'),
        ),
    ]
