# Generated by Django 4.1.1 on 2023-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0055_alter_carrusel_productos_show_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel_productos',
            name='descripción',
            field=models.TextField(blank=True, null=True),
        ),
    ]
