# Generated by Django 4.1.1 on 2023-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0056_alter_carrusel_productos_descripción'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Página Home/Noticias/')),
                ('Introducción_de_Noticia', models.TextField(max_length=200)),
                ('Continuación_de_Noticia', models.TextField()),
                ('Fecha', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticia',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Noticia_1',
        ),
        migrations.DeleteModel(
            name='Noticia_2',
        ),
        migrations.DeleteModel(
            name='Noticia_3',
        ),
    ]
