# Generated by Django 4.1.1 on 2023-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0057_noticia_delete_noticia_1_delete_noticia_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Mostrar Noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(default='../static/img/logo/logoAicros2.png', upload_to='Página Home/Noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='título',
            field=models.CharField(default='Noticia <built-in function id>', max_length=150),
        ),
    ]
