# Generated by Django 4.1.1 on 2023-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0058_noticia_show_alter_noticia_foto_alter_noticia_título'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='título',
            field=models.CharField(default='Nueva Noticia', max_length=150),
        ),
    ]
