# Generated by Django 4.1.1 on 2023-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0059_alter_noticia_título'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(default='../static/img/AicrosIdentificador.png', upload_to='Página Home/Noticias/'),
        ),
    ]
