# Generated by Django 4.1.1 on 2023-04-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0060_alter_noticia_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cifra',
            options={'ordering': ['id'], 'verbose_name': 'Cifra', 'verbose_name_plural': 'Cifra'},
        ),
    ]
