# Generated by Django 4.1.1 on 2023-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0061_alter_cifra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alianza',
            name='nombre',
            field=models.CharField(default='Alianza de Aicros', max_length=100),
        ),
    ]
