# Generated by Django 4.1.1 on 2023-04-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0062_alianza_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cifra',
            options={'ordering': ['título'], 'verbose_name': 'Cifra', 'verbose_name_plural': 'Cifra'},
        ),
    ]
