# Generated by Django 4.1.1 on 2023-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0063_alter_cifra_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Alianzas',
                'verbose_name_plural': 'Texto para título de Alianzas',
                'db_table': 'index_title_alliance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BussinesLinesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Lineas de negocio',
                'verbose_name_plural': 'Texto para título de Lineas de negocio',
                'db_table': 'index_title_buss_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Noticias',
                'verbose_name_plural': 'Texto para título de Noticias',
                'db_table': 'index_title_news',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Productos',
                'verbose_name_plural': 'Texto para título de Productos',
                'db_table': 'index_title_products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Promociones',
                'verbose_name_plural': 'Texto para título de Promociones',
                'db_table': 'index_title_promotions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Servicios',
                'verbose_name_plural': 'Texto para título de Servicios',
                'db_table': 'index_title_services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StatsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de La empresa en cifras',
                'verbose_name_plural': 'Texto para título de La empresa en cifras',
                'db_table': 'index_title_stats',
                'ordering': ['id'],
            },
        ),
    ]
