# Generated by Django 4.1.1 on 2023-05-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0064_alliancetitle_bussineslinestitle_newstitle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsTitle',
        ),
        migrations.DeleteModel(
            name='ServicesTitle',
        ),
    ]
