# Generated by Django 4.1.1 on 2023-06-06 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0065_delete_productstitle_delete_servicestitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['Fecha'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticia'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 8, 53, 18, 244800)),
        ),
    ]
