# Generated by Django 4.1.1 on 2023-06-06 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0067_alter_noticia_options_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
