# Generated by Django 4.1.1 on 2023-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0068_alter_noticia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_negrita', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Banner',
                'verbose_name_plural': 'Texto para título de Banner',
                'ordering': ['id'],
            },
        ),
    ]
