# Generated by Django 4.1.1 on 2023-06-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0069_bannertitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrusel_Productos',
        ),
        migrations.DeleteModel(
            name='Carrusel_Servicios',
        ),
    ]
