# Generated by Django 4.1.1 on 2023-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0070_delete_carrusel_productos_delete_carrusel_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(default='Página no encontrada!', max_length=100)),
                ('foto', models.ImageField(blank=True, default='../static/img/logo/invertido.png', upload_to='Página Home/')),
            ],
            options={
                'verbose_name': 'página 404',
                'ordering': ['id'],
            },
        ),
    ]
