# Generated by Django 4.2.2 on 2023-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion_Productos_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
            ],
            options={
                'verbose_name': 'Descripción Productos Aicros',
                'verbose_name_plural': 'Descripción Productos Aicros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Descripcion_Productos_Distribuidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
            ],
            options={
                'verbose_name': 'Descripción Productos Distribuidos',
                'verbose_name_plural': 'Descripción Productos Distribuidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Encabezado_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto1', models.TextField()),
                ('texto2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Producto',
                'verbose_name_plural': 'Encabezado Producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Página Productos/Aicros/Imágenes/Imágenes')),
                ('foto_carrusel', models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Página Productos/Aicros/Imágenes/Imágenes', verbose_name='Foto Carrusel')),
                ('show', models.BooleanField(default=True, verbose_name='Mostrar en carrusel')),
                ('show_text', models.BooleanField(default=True, verbose_name='Mostrar texto')),
                ('show_image', models.BooleanField(default=True, verbose_name='Mostrar imagen')),
                ('título', models.CharField(blank=True, max_length=200, null=True)),
                ('resumen', models.TextField(default=models.CharField(blank=True, max_length=200, null=True), max_length=200)),
                ('descripción', models.TextField()),
                ('ícono', models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Ícono')),
                ('nombre_Botón', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Productos Aicros',
                'verbose_name_plural': 'Productos Aicros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Distribuido_Aicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Página Productos/Aicros/Distribuidos/Imágenes')),
                ('foto_carrusel', models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Página Productos/Aicros/Distribuidos/Imágenes', verbose_name='Foto Carrusel')),
                ('show', models.BooleanField(default=True, verbose_name='Mostrar en carrusel')),
                ('show_text', models.BooleanField(default=True, verbose_name='Mostrar texto')),
                ('show_image', models.BooleanField(default=True, verbose_name='Mostrar imagen')),
                ('título', models.CharField(blank=True, max_length=200, null=True)),
                ('resumen', models.TextField(default=models.CharField(blank=True, max_length=200, null=True), max_length=200)),
                ('descripción', models.TextField()),
                ('ícono', models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Distribuidos/Ícono')),
                ('nombre_Botón', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Producto Distribuido',
                'verbose_name_plural': 'Producto Distribuido',
                'ordering': ['id'],
            },
        ),
    ]
