# Generated by Django 4.2.2 on 2023-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_aicros',
            name='nombre_Botón',
        ),
        migrations.RemoveField(
            model_name='producto_aicros',
            name='ícono',
        ),
        migrations.RemoveField(
            model_name='producto_distribuido_aicros',
            name='nombre_Botón',
        ),
        migrations.RemoveField(
            model_name='producto_distribuido_aicros',
            name='ícono',
        ),
        migrations.AlterField(
            model_name='producto_aicros',
            name='foto',
            field=models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Pagina-Productos/Aicros/Imágenes/Imágenes'),
        ),
        migrations.AlterField(
            model_name='producto_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Pagina-Productos/Aicros/Imágenes/Imágenes', verbose_name='Foto Carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='foto',
            field=models.ImageField(default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Pagina-Productos/Aicros/'),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, default='../static_Server/img/logo/aicros-logo.jpg', upload_to='Pagina-Productos/Aicros/', verbose_name='Foto Carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='resumen',
            field=models.TextField(default=models.CharField(default='producto distribuido', max_length=200), max_length=200),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='título',
            field=models.CharField(default='producto distribuido', max_length=200),
        ),
    ]
