# Generated by Django 4.1.1 on 2023-03-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_distribuido_aicros_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_aicros',
            name='resumen',
            field=models.TextField(default=models.CharField(blank=True, max_length=200, null=True), max_length=200),
        ),
        migrations.AddField(
            model_name='producto_distribuido_aicros',
            name='resumen',
            field=models.TextField(default=models.CharField(blank=True, max_length=200, null=True), max_length=200),
        ),
    ]
