# Generated by Django 4.1.1 on 2023-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_aicros_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_aicros',
            name='foto',
            field=models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Imágenes'),
        ),
        migrations.AlterField(
            model_name='producto_aicros',
            name='ícono',
            field=models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Ícono'),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='foto',
            field=models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Distribuidos/Imágenes'),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='ícono',
            field=models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Distribuidos/Ícono'),
        ),
    ]
