# Generated by Django 4.1.1 on 2023-06-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_producto_aicros_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto_aicros',
            options={'ordering': ['id'], 'verbose_name': 'Productos Aicros', 'verbose_name_plural': 'Productos Aicros'},
        ),
    ]
