# Generated by Django 4.1.1 on 2023-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_producto_aicros_foto_carrusel_producto_aicros_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_aicros',
            name='foto',
            field=models.ImageField(blank=True, default='../static/img/AicrosIdentificador.png', upload_to='Página Productos/Aicros/Imágenes/Imágenes'),
        ),
    ]
