# Generated by Django 4.1.1 on 2023-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_producto_aicros_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_aicros',
            name='foto',
            field=models.ImageField(blank=True, default='../static/img/logo/aicros-logo.png', upload_to='Página Productos/Aicros/Imágenes/Imágenes'),
        ),
        migrations.AlterField(
            model_name='producto_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, default='../static/img/logo/aicros-logo.png', upload_to='Página Productos/Aicros/Imágenes/Imágenes', verbose_name='Foto Carrusel'),
        ),
        migrations.AlterField(
            model_name='producto_distribuido_aicros',
            name='foto_carrusel',
            field=models.ImageField(blank=True, default='../static/img/logo/aicros-logo.png', upload_to='Página Productos/Aicros/Distribuidos/Imágenes', verbose_name='Foto Carrusel'),
        ),
    ]
