# Generated by Django 4.2.2 on 2023-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anno_Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('número', models.IntegerField()),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Año de Historia',
                'verbose_name_plural': 'Año de Historia',
                'ordering': ['número'],
            },
        ),
        migrations.CreateModel(
            name='Encabezado_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('texto_1', models.TextField()),
                ('texto_2', models.TextField()),
            ],
            options={
                'verbose_name': 'Encabezado Nosotros',
                'verbose_name_plural': 'Encabezado Nosotros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField(max_length=430)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Evento',
                'ordering': ['título'],
            },
        ),
        migrations.CreateModel(
            name='EventsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Eventos',
                'verbose_name_plural': 'Texto para título de Eventos',
                'db_table': 'about_us_title_events',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Historia',
                'verbose_name_plural': 'Texto para título de Historia',
                'db_table': 'about_us_title_history',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Miembro_de_Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Página Nosotros/Miembro de Trabajo/Imágenes')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Miembro de Trabajo',
                'verbose_name_plural': 'Miembro de Trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mision_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misión',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MissionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Mision, Vision y Valores',
                'verbose_name_plural': 'Texto para título de Mision, Vision y Valores',
                'db_table': 'about_us_title_mission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeLapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fyear', models.CharField(blank=True, default='', max_length=8, verbose_name='año de inicio')),
                ('lyear', models.CharField(blank=True, default='', max_length=8, verbose_name='año de fin')),
            ],
            options={
                'verbose_name': 'Cronología',
                'verbose_name_plural': 'Cronología',
                'ordering': ['fyear'],
            },
        ),
        migrations.CreateModel(
            name='Valores_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Valores',
                'verbose_name_plural': 'Valores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vision_Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
            options={
                'verbose_name': 'Visión',
                'verbose_name_plural': 'Visión',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkTeamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Equipo de trabajo',
                'verbose_name_plural': 'Texto para título de Equipo de trabajo',
                'db_table': 'about_us_title_workteam',
                'ordering': ['id'],
            },
        ),
    ]
