# Generated by Django 4.2.2 on 2023-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro_de_trabajo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Pagina-Nosotros/Miembro-de-Trabajo'),
        ),
    ]
