# Generated by Django 4.1.1 on 2023-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0003_alter_evento_options_alter_evento_descripción'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anno_historia',
            name='número',
            field=models.IntegerField(),
        ),
    ]
