# Generated by Django 4.1.1 on 2023-05-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0004_alter_anno_historia_número'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Eventos',
                'verbose_name_plural': 'Texto para título de Eventos',
                'db_table': 'about_us_title_events',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Historia',
                'verbose_name_plural': 'Texto para título de Historia',
                'db_table': 'about_us_title_history',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MissionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Mision, Vision y Valores',
                'verbose_name_plural': 'Texto para título de Mision, Vision y Valores',
                'db_table': 'about_us_title_mission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkTeamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Equipo de trabajo',
                'verbose_name_plural': 'Texto para título de Equipo de trabajo',
                'db_table': 'about_us_title_workteam',
                'ordering': ['id'],
            },
        ),
    ]
