# Generated by Django 4.1.1 on 2023-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0005_eventstitle_historytitle_missiontitle_workteamtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fyear', models.IntegerField()),
                ('lyear', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cronología',
                'verbose_name_plural': 'Cronología',
                'ordering': ['fyear'],
            },
        ),
    ]
