# Generated by Django 4.1.1 on 2023-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nosotros', '0008_alter_timelapse_fyear_alter_timelapse_lyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelapse',
            name='fyear',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='año de inicio'),
        ),
        migrations.AlterField(
            model_name='timelapse',
            name='lyear',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='año de fin'),
        ),
    ]
