# Generated by Django 4.1.1 on 2023-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('radio', 'Selección única'), ('checkbox', 'Selección múltiple'), ('text', 'Cuadro de texto'), ('textarea', 'Área de texto'), ('date', 'Fecha'), ('email', 'Correo'), ('number', 'Número'), ('tel', 'Teléfono'), ('color', 'Color')], max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('respuestas', models.ManyToManyField(to='Encuestas.respuesta')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('encabezado', models.TextField(blank=True)),
                ('pie', models.TextField(blank=True, max_length=100)),
                ('preguntas', models.ManyToManyField(to='Encuestas.pregunta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
