# Generated by Django 4.2.2 on 2023-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo', models.CharField(choices=[('radio', 'Selección única'), ('checkbox', 'Selección múltiple'), ('text', 'Cuadro de texto'), ('textarea', 'Área de texto'), ('date', 'Fecha'), ('email', 'Correo'), ('number', 'Número'), ('tel', 'Teléfono'), ('color', 'Color')], max_length=30)),
                ('orden', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Encuestas',
                'verbose_name_plural': 'Texto para título de Encuestas',
                'db_table': 'survey_title_survey',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=999)),
                ('orden', models.IntegerField()),
                ('grupo_de_respuestas', models.ManyToManyField(blank=True, to='Encuestas.grupoderespuestas', verbose_name='grupo de respuestas')),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='grupoderespuestas',
            name='respuestas',
            field=models.ManyToManyField(blank=True, to='Encuestas.respuesta'),
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('encabezado', models.TextField(blank=True)),
                ('pie', models.TextField(blank=True, max_length=200)),
                ('preguntas', models.ManyToManyField(blank=True, to='Encuestas.pregunta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
