# Generated by Django 4.1.1 on 2023-04-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='pie',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='titulo',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='tipo',
            field=models.CharField(choices=[('radio', 'Selección única'), ('checkbox', 'Selección múltiple'), ('text', 'Cuadro de texto'), ('textarea', 'Área de texto'), ('date', 'Fecha'), ('email', 'Correo'), ('number', 'Número'), ('tel', 'Teléfono'), ('color', 'Color')], max_length=30),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
