# Generated by Django 4.1.1 on 2023-04-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0002_alter_encuesta_nombre_alter_encuesta_pie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['tipo']},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='titulo_interno',
            field=models.CharField(default='', max_length=999),
        ),
    ]
