# Generated by Django 4.1.1 on 2023-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0003_alter_respuesta_options_pregunta_titulo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='titulo_interno',
            field=models.CharField(default='', max_length=999, unique=False),
        ),
    ]
