# Generated by Django 4.1.1 on 2023-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0005_remove_pregunta_titulo_interno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
