# Generated by Django 4.1.1 on 2023-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0006_alter_pregunta_options_alter_respuesta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['tipo', 'orden']},
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='Encuestas.pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuestas',
            field=models.ManyToManyField(blank=True, to='Encuestas.respuesta'),
        ),
    ]
