# Generated by Django 4.1.1 on 2023-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0007_alter_respuesta_options_alter_encuesta_preguntas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['valor']},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuestas',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='grupo_de_respuestas',
            field=models.ManyToManyField(blank=True, to='Encuestas.respuesta', verbose_name='grupo de respuestas'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GrupoDeRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tipo', models.CharField(choices=[('radio', 'Selección única'), ('checkbox', 'Selección múltiple'), ('text', 'Cuadro de texto'), ('textarea', 'Área de texto'), ('date', 'Fecha'), ('email', 'Correo'), ('number', 'Número'), ('tel', 'Teléfono'), ('color', 'Color')], max_length=30)),
                ('orden', models.IntegerField(default=1)),
                ('respuestas', models.ManyToManyField(blank=True, to='Encuestas.respuesta')),
            ],
        ),
    ]
