# Generated by Django 4.1.1 on 2023-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0008_alter_respuesta_options_remove_pregunta_respuestas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='grupo_de_respuestas',
            field=models.ManyToManyField(blank=True, to='Encuestas.grupoderespuestas', verbose_name='grupo de respuestas'),
        ),
    ]
