# Generated by Django 4.1.1 on 2023-05-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0009_alter_pregunta_grupo_de_respuestas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['orden']},
        ),
    ]
