# Generated by Django 4.1.1 on 2023-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0010_alter_pregunta_options_alter_respuesta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Texto para título de Encuestas',
                'verbose_name_plural': 'Texto para título de Encuestas',
                'db_table': 'survey_title_survey',
                'ordering': ['id'],
            },
        ),
    ]
